import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ShopProvider } from "@/context/ShopContext";
import { BuildProvider } from "@/context/BuildContext";
import Navbar from "@/components/Navbar";

import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";
import CartDrawer from "@/components/CartDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShopProvider>
          <BuildProvider>
            
            <main className="min-h-screen pb-16 md:pb-0">
              {children}
            </main>
            <CartDrawer />
            
            <Toaster />
          </BuildProvider>
        </ShopProvider>
      </body>
    </html>
  );
}
